from enum import IntEnum


class GameStatus(IntEnum):
    UNKNOWN = 0
    FIRST_PAGE_IS_PRESENTED = 1
    NEXT_LEVEL_DIALOG_IS_PRESENTED = 2
    GAME_IS_RUNNING = 3
    GAME_IS_PAUSED = 4
    OPTIONS_DIALOG_IS_PRESENTED = 5
    LEVEL_COMPLETED_DIALOG_IS_PRESENTED = 6
    GAME_OVER_DIALOG_IS_PRESENTED = 7

