import pygame
from debug import Debug

# Clock
FPS = 60

# Screen size
WIDTH = 1024
HEIGHT = 600
# Dashboard size
DASHBOARD_HEIGHT = 150

# Tile size
TILE_SIZE = 64

# Events
GAME_OVER_EVENT = pygame.USEREVENT + 1
ADD_DIAMOND_EVENT = pygame.USEREVENT + 2
DECREASE_ENERGY_EVENT = pygame.USEREVENT + 3
CHANGE_POWER_EVENT = pygame.USEREVENT + 4
EXIT_POINT_IS_OPEN_EVENT = pygame.USEREVENT + 5
NEXT_LEVEL_EVENT = pygame.USEREVENT + 6
REFRESH_OBSTACLE_MAP_EVENT = pygame.USEREVENT + 7
PLAYER_TILE_POSITION_CHANGED_EVENT = pygame.USEREVENT + 8

# Create debugger
debugger = Debug()
