from enum import StrEnum


class SoundEffect(StrEnum):
    COLLECT_DIAMOND = 'collect_diamond'
    COLLECT_KEY = 'collect_key'
    COLLECT_BOW = 'collect_bow'
    COLLECT_SWORD = 'collect_sword'
    COLLECT_EXPLOSION = 'collect_explosion'
    COLLECT_ENERGY = 'collect_energy'
    COLLECT_LIFE = 'collect_life'
    COLLECT_CHECKPOINT = 'collect_checkpoint'
    COLLECT_LIGHTNING_SPELL = 'collect_lighting_spell'
    COLLECT_LIGHTNING_SPELL_TWILIGHT = 'collect_lighting_spell_twilight'
    COLLECT_EGG = 'collect_egg'

    STRIKE_WITH_SWORD = 'strike_with_sword'
    SHOOT_ARROW = 'shoot_arrow'
    EXPLODE = 'explode'
    COLLIDE_ARROW_WITH_OBSTACLE = 'collide_arrow_with_obstacle'
    COLLIDE_FIREBALL_WITH_OBSTACLE = 'collide_fireball_with_obstacle'
    COLLIDE_PLAYER_WITH_ENEMY = 'collide_player_with_enemy'
    COLLIDE_PLAYER_WITH_HOSTILE_FORCE = 'collide_player_with_hostile_force'
    DECREASE_ENEMY_ENERGY_USING_SWORD = 'decrease_enemy_energy_using_sword'
    DECREASE_ENEMY_ENERGY_USING_BOW = 'decrease_enemy_energy_using_bow'
    DECREASE_ENEMY_ENERGY_USING_EXPLOSION = 'decrease_enemy_energy_using_explosion'
    KILL_ENEMY = 'kill_enemy'
    KILL_OCTOPUS = 'kill_octopus'

    MOVE_PLAYER = 'move_player'
    MOVE_OBSTACLE = 'move_obstacle'
    MOVE_ENEMY = 'move_enemy'
    CHANGE_WEAPON = 'change_weapon'
    DEMOLISH_WALL = 'demolish_wall'
    OPEN_DOOR = 'open_door'
    TELEPORT = 'teleport'
    CREATE_MONSTER = 'create_monster'
    SHOW_EXIT_POINT = 'show_exit_point'
    COMPLETE_LEVEL = 'complete_level'
    LOST_LIFE = 'lost_life'
