import pygame


class Events:
    GAME_OVER_EVENT = pygame.event.custom_type()
    GAME_OVER_SUMMARY_EVENT = pygame.event.custom_type()
    YOU_WIN_EVENT = pygame.event.custom_type()
    YOU_WIN_SUMMARY_EVENT = pygame.event.custom_type()
    COLLECT_DIAMOND_EVENT = pygame.event.custom_type()
    COLLECT_KEY_EVENT = pygame.event.custom_type()
    CHANGE_WEAPON_CAPACITY_EVENT = pygame.event.custom_type()
    CHANGE_ENERGY_EVENT = pygame.event.custom_type()
    CHANGE_WEAPON_EVENT = pygame.event.custom_type()
    EXIT_POINT_IS_OPEN_EVENT = pygame.event.custom_type()
    START_TELEPORT_PLAYER_TO_NEXT_LEVEL_EVENT = pygame.event.custom_type()
    FINISH_TELEPORT_PLAYER_TO_NEXT_LEVEL_EVENT = pygame.event.custom_type()
    NEXT_LEVEL_EVENT = pygame.event.custom_type()
    REFRESH_OBSTACLE_MAP_EVENT = pygame.event.custom_type()
    PLAYER_TILE_POSITION_CHANGED_EVENT = pygame.event.custom_type()
    PLAYER_IS_NOT_USING_WEAPON_EVENT = pygame.event.custom_type()
    ADD_TOMBSTONE_EVENT = pygame.event.custom_type()
    ADD_BOSS_TOMBSTONE_EVENT = pygame.event.custom_type()
    ADD_VANISHING_POINT_EVENT = pygame.event.custom_type()
    CREATE_EGG_EVENT = pygame.event.custom_type()
    CREATE_MONSTER_EVENT = pygame.event.custom_type()
    CREATE_BOSS_OCTOPUS_EVENT = pygame.event.custom_type()
    ADD_PARTICLE_EFFECT_EVENT = pygame.event.custom_type()
    PARTICLE_EVENT = pygame.event.custom_type()
    PLAYER_LOST_LIFE_EVENT = pygame.event.custom_type()
    TELEPORT_PLAYER_EVENT = pygame.event.custom_type()
    RESPAWN_PLAYER_EVENT = pygame.event.custom_type()
    COLLECT_LIFE_EVENT = pygame.event.custom_type()
    CHANGE_SCORE_EVENT = pygame.event.custom_type()
    CREATE_EXPLODE_EFFECT_EVENT = pygame.event.custom_type()
    REMOVE_OBSTACLES_EVENT = pygame.event.custom_type()
    TILT_EFFECT_EVENT = pygame.event.custom_type()
